### ISSUE TITLE
KiCad file

### ISSUE THREAD

**Issue by Poechi** [Snackya/Snackboard-mix#1]
Do you have the KiCad project file for this project? I would like different icons below the faders. 
Thank you.

**Comment by Snackya** [comment]
Sorry for not including them originally. I had to clean up some unused legacy files for licensing reasons first.
KiCad project files have been added as of 3d74514321407cc8a0384599fe86aa4659222d7b .
If you want to replace the icons on the PCB, simply delete the footprint in Pcbnew, convert an image to a .kicad_mod file using KiCad's Bitmap to Component converter and add the resulting file to the PCB.
